### ISSUE TITLE
Support responsive Ads

### ISSUE THREAD

**Issue by adam1920** [scttcper/ng2-adsense#107]
Thanks for this amazing plugin!
Can this plugin support responsive ads with format "auto" (without predefined "width")?

i.e. ad code:
<ins class="adsbygoogle"
     style="display:block"
     data-ad-client="ca-pub-XXXXXXXXXXXXX"
     data-ad-slot="XXXXXXXXXXX"
     data-ad-format="**auto**"></ins>

**Comment by adam1920** [comment]
Sorry, my bad, I see by default it's responsive ads. You can close this issue

**Comment by ksrvnn03** [comment]
Create responsive ads with defined width, height, and format, this possible in ng2-adsense ?
