### ISSUE TITLE
Large Mobile Banner 320x100 has incorrect markup

### ISSUE THREAD

**Issue by naveedahmed1** [scttcper/ng2-adsense#110]
Adding a large Mobile Banner 320x100 like below generates incorrect markup:

`<ng2-adsense [adSlot]="12324243" [display]="'inline-block'" [width]="320" [height]="100"></ng2-adsense>`

The generated markup contains `data-ad-format="auto"` which it shouldn't.

**Comment by scttcper** [comment]
the default is auto if you don't set it to something else

**Comment by naveedahmed1** [comment]
What should we do in this case? The markup from Adsense for Large Mobile Banner 320x100 is:

```
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<ins class="adsbygoogle"
     style="display:inline-block;width:320px;height:100px"
     data-ad-client="ca-pub-4545434543543"
     data-ad-slot="5654656"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

To generate this I added below to my component:

`<ng2-adsense [adSlot]="12324243" [display]="'inline-block'" [width]="320" [height]="100"></ng2-adsense>`


But this results in markup with `ins`: 

`  <ins class="adsbygoogle" data-ad-client="ca-pub-4545434543543" data-ad-slot="5654656" data-ad-format="auto" data-ad-region="page-34343" data-adsbygoogle-status="done" style="display: inline-block; width: 384px; height: 100px; margin-left: -31px; z-index: 30;">`

My ad unit is inside a Material2 card `mat-card`.

When I preview the ad on mobile its stretched and moved outside of card boundaries. Probably because the generated styles have different width `width: 384px;` instead of `width:320px;`

**Comment by scttcper** [comment]
maybe try [adFormat]="null"

**Comment by naveedahmed1** [comment]
I don't think it will work, this will assign `auto` (https://github.com/scttcper/ng2-adsense/blob/22fb12d1b8b1f50fe0350f92735e33fc3ddf45bf/src/lib/ng2-adsense.ts#L82)

`    this.adFormat = use(this.adFormat, config.adFormat || 'auto');
`

**Comment by scttcper** [comment]
the `||` is only for the default value since i want the global config to override it. the `use()` function should allow for null or false values

**Comment by naveedahmed1** [comment]
What if you could update it such that  when `[adFormat]="null"` it doesn't add `data-ad-format` attribute to `ins`.

**Comment by naveedahmed1** [comment]
I have tested ` [adFormat]="null"` but its still adding `data-ad-format="auto"`

**Comment by scttcper** [comment]
`[adFormat]="null"` works as expected for me and does not have the data-ad-format attribute
