### ISSUE TITLE
Not working for app

### ISSUE THREAD

**Issue by skyrocket777** [scttcper/ng2-adsense#137]
I installed correctly the plugin
I am able to see the adds in the computer. But not in the Android devices (I've tested in a couple)
I wonder if this plugin is still functional. Greetings

**Comment by scttcper** [comment]
should be working yeah

**Comment by skyrocket777** [comment]
I'm using it in an Ionic 3 proyect and it shows nothing :s
Visible in PC, empty in smartphone devise
Is there any special configuration needed, example for Android?
Greetings

**Comment by scttcper** [comment]
Ionic will probably require something custom with adsense, especially on mobile.
