### ISSUE TITLE
Ads don't load when navigating to a page normally, but they work when navigating with routerlink.

### ISSUE THREAD

**Issue by Metsuryu** [scttcper/ng2-adsense#142]
I just added ng2-adsense to my project, and at first I didn't think it worked, then I navigated way from the page using a routerLink link, and came back to it, and the ad was there.

I tested it a bit more, and I found that the ad only loads when I navigate to the page via routerLink, but it doesn't work when I refresh the page, or I navigate to it with a normal link.

Edit: That seems to happen because of the "async" loading of the adsense script.
Removing the "async" lets ads load even when navigating to them without routerLink, but that's not ideal, as synchronous loading of scripts is bad for performance.

**Comment by scttcper** [comment]
I had a timeout to retry the activating of the ad, but if adsense loaded slower than the timeout then it still wouldn't load. Can now configure timeOutRetry to whatever you think works. I had 200 since it usually loads before then.

**Comment by Metsuryu** [comment]
That's great thank you.

How do I set the timeout?

Anyway, to make it more reliable and consistent, maybe you could add an event listener to check when the script is loaded, or check again a few times with some delay?

**Comment by scttcper** [comment]
either [timeOutRetry] on component or forRoot({timeOutRetry: number})

**Comment by Metsuryu** [comment]
Oh, I forgot to update ng2-adsense before doing that. Now it works, thanks.

**Comment by Easyschools** [comment]
is there way to fix this issue with timeout retry as I use ssr and the rendered page in the server have to wait for the 15 sec. I gave and then it render the page?
