### ISSUE TITLE
[adClient] and [adSlot] don't seem to work when passing a variable to them.

### ISSUE THREAD

**Issue by Metsuryu** [scttcper/ng2-adsense#153]
When used like this they work fine:

```
<ng-adsense
  [adClient]="'ca-pub-7640562161899788'"
  [adSlot]="7259870550"
</ng-adsense>
```

But I need to use different adClient and adSlot dynamically, so I need to use variables, that would be something like this in the .ts file:

```
testAdClientID: "ca-pub-7640562161899788";
testAdSlotID: "7259870550";
```

and use it like so:
```
  <ng-adsense 
  [adClient]="testAdClientID"
  [adSlot]="testAdSlotID"
  ></ng-adsense>
```

But it doesn't seem to work. It keeps using the defaults, like when I don't pass anything at all.

**Comment by scttcper** [comment]
It’s only set onInit so if you’re setting them later you should put an ngIf or something on the component until you’re ready to pass the values.

**Comment by Metsuryu** [comment]
I'll try that tomorrow, thank you!

**Comment by Metsuryu** [comment]
Oh wow that's embarrassing, I just realized I used `:` instead of `=` on those test variables, that's why it didn't work.

I guess I was tired.

Using the ngIf worked, thank you!
