### ISSUE TITLE
Support test mode

### ISSUE THREAD

**Issue by kaynz** [scttcper/ng2-adsense#162]
Hi,

could you support test mode for AdSense?

You can enable it setting `data-ad-test="on"`.

Thanks.

**Comment by kaynz** [comment]
@scttcper I think there's a small typo, it should be `[attr.data-ad-test]="adtest"`.

**Comment by scttcper** [comment]
data-ad-test didn't do anything for me. data-adtest changed the parameters when calling back to google. as far as i can tell adtest is the only offical one https://github.com/ampproject/amphtml/pull/3040/files

**Comment by kaynz** [comment]
Okay, I will test the current state and provide feedback. 👍

**Comment by kaynz** [comment]
I set `adtest: 'on'` in my `app.component.ts` but can't see ads on my dev environment =/

**Comment by scttcper** [comment]
i got the same thing i always get w/ localhost. just the default background color i chose. there's more references to adtest for different kinds of ads. https://developers.google.com/custom-search-ads/docs/reference
