### ISSUE TITLE
Adsense not work for my projects :(

### ISSUE THREAD

**Issue by tudolinux** [scttcper/ng2-adsense#163]
Hi, how are you?
I'm Luciano, i'm from Brazyl and using angular in my projects. In 2 projects í'm using ng2-adsense and this not work very well, see the example please.

http://novo.maisreceitas.com.br

if i click in the link, thats ok, working perfect, but, if i click in menu "Paginas" only external adsense work and not work in pagina.component.html. If i click in pagina menu not working only internal adsense, but, if i refresh page in pagina, all adsense not working.

My app.module.ts

import { HomeComponent } from './home/home.component';
import { PaginaComponent } from './pagina/pagina.component';
import { BrowserModule } from '@angular/platform-browser';
import { NgModule } from '@angular/core';
import { AdsenseModule } from 'ng2-adsense';
import { RouterModule, Routes } from '@angular/router';

import { AppComponent } from './app.component';

const routes: Routes = [
  { path: '', component: HomeComponent },
  { path: 'home', component: HomeComponent },

  { path: 'pagina/:id', component: PaginaComponent }
];

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    PaginaComponent
  ],
  imports: [
    BrowserModule,
    RouterModule.forRoot(routes),
    // shown passing optional global defaults
    AdsenseModule.forRoot({
      adClient: 'ca-pub-0338836461603030',
      adSlot: 6163597024,
    })
  ],
  providers: [],
  bootstrap: [AppComponent]
})
export class AppModule { }

..................

My app.component.html

<h1>Teste adsense</h1>
<a routerLink="/home">Home</a>
<a routerLink="/pagina/1">Páginas</a>

<div style="border: 1px solid;">
  <router-outlet></router-outlet>
</div>

<h2>Adsense adicionado no app.component.html</h2>
<ng-adsense></ng-adsense>

....................

my home.component.html

<h2>Adsense interna Home</h2>
<ng-adsense></ng-adsense>

.....................

my pagina.component.html

<h2>Adsense interna da Página</h2>
<ng-adsense></ng-adsense>

Thank you for ng2-adsense and thanks for read my bad english :)

**Comment by tudolinux** [comment]
A observation!

My chrome navigator has adblock add-on installed and ng2-adsense work perfect, only adblock installed,  my other machine with chrome and don't adblock, ocorreing the problem.

**Comment by tudolinux** [comment]
Hi!
I'm doing some tests ...

http://novo.maisreceitas.com.br/pagina/1 for me it works;
http://novo.maisreceitas.com.br/pagina/2 for me it works;
http://novo.maisreceitas.com.br/pagina/3 for me does not work;

Some dynamic pages work, some do not.

By default installed angular 5.2.0, I changed to 4.0.0 and the problem continues.

Recalling that the ng2-adsense demo link works perfectly and browser with the adblock add-on installed also works normal.

I have the impression that gives problem with the script
<script async src = // pagead2.googlesyndication.com/pagead/js/adsbygoogle.js> </ script>

Without it does not display, so does dynamic pages.

Hugs

**Comment by scttcper** [comment]
let me know if you think something in the codebase should change.
