### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by Hacksore** [scttcper/ng2-adsense#213]
So far I am seeing crazy memory leaks with my current webapp and it looks to be related to adsense/ng-adsense. When I turn on my adblocker the memory does not grow exponentially but when it's off navigating pages skyrockets the page memory.

I do use the loading method of *ngIf="!loading" so that page changes refresh the ad but even trying to disabling that I still had seen the memory grow.

Here is me doing about 10-20 page changes on the production webapp (https://mcskinsearch.com/browse):
![image](https://user-images.githubusercontent.com/996134/39097969-46df0dbe-4629-11e8-8909-49ad8bf01e58.png)

Same test as above with uBlock turned on:
![image](https://user-images.githubusercontent.com/996134/39097970-4d807ffe-4629-11e8-8ec1-8408494d20ac.png)

If any further information is needed please let me know.

Thanks!

**Comment by scttcper** [comment]
hey took a stab at it and released it under 5.3.0

I'm seeing it still hogs memory but it does look like it might now release some of it. 

![screen shot 2018-04-27 at 10 45 42 am](https://user-images.githubusercontent.com/1400464/39377276-6416aa98-4a09-11e8-8865-98152ea8c95b.png)

**Comment by Hacksore** [comment]
I'll update to 5.3.0 and let you know what I see. Thanks for looking into this!
