### ISSUE TITLE
Only one instance seems to work.

### ISSUE THREAD

**Issue by salvdev** [scttcper/ng2-adsense#22]
I can only get one instance to work. I'm trying to place multiple ads in div but only the first ad appears.

```
    <div style="width: 300px;  height:1250px; margin-left: 10px;
    margin-top: 54px; float: right;">

      <ng2-adsense [adClient]="'ca-pub-XXXXXXXXXXXXXXXX'" [adSlot]="1212121212"> </ng2-adsense>
      <br>
      <ng2-adsense [adClient]="'ca-pub-XXXXXXXXXXXXXXXX'" [adSlot]="3434343434"> </ng2-adsense>
    </div>
```
Does ng2-adsense only support 1 ad at a time?

**Comment by scttcper** [comment]
put two on the github pages example. https://scttcper.github.io/ng2-adsense/1
seems fine. could not showing up if your ad slot code is new

**Comment by salvdev** [comment]
Oh you're right. Seems there was some delay on the second ad displaying, thanks. Awesome module btw.
