### ISSUE TITLE
No support for "enable_page_level_ads"?

### ISSUE THREAD

**Issue by BamiGorengo** [scttcper/ng2-adsense#256]
I created a new ad on adsense, this needs a `enable_page_level_ads: true` Can you please add this to the package? :)

**Comment by scttcper** [comment]
https://github.com/scttcper/ng2-adsense/blob/master/src/lib/adsense.component.ts#L50

`[pageLevelAds]="true"`

**Comment by BamiGorengo** [comment]
hm.. Thanks. but i realize now that its not possible to place adds on PWA pages...

**Comment by scttcper** [comment]
page level ads might not work that great. normal ads are fine.
