### ISSUE TITLE
Support data-full-width-responsive

### ISSUE THREAD

**Issue by doonot** [scttcper/ng2-adsense#306]
Thank you very much for this library! I would appreciate it if you could add support for full width responsive ads.

According to Google this can be done through this parameter:

```
<ins class="adsbygoogle"
    style="display:block;"
    data-ad-client="ca-pub-1234"
    data-ad-slot="5678"
    data-ad-format="auto"
     data-full-width-responsive="true"></ins>
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<script>(adsbygoogle = window.adsbygoogle || []).push({});
</script>
```

Best regards, Patrick

**Comment by hendrickcastro** [comment]
What´s news?

**Comment by lukaszgodula** [comment]
I have solution locally, @scttcper could you add me to contributors to push branch and make PR?

**Comment by scttcper** [comment]
Make a fork and create a pr like normal

**Comment by lukaszgodula** [comment]
Ok, I've submitted PR.

**Comment by scttcper** [comment]
#314
