### ISSUE TITLE
Ads are not shown

### ISSUE THREAD

**Issue by DMZakaria** [scttcper/ng2-adsense#340]
I did Import the module in app.module.ts and I inject the following code in my component
 ``` <ng-adsense [adSlot]="xxxxxxxxx" [display]="'inline-block'"> </ng-adsense> ```

I can see the `<ins>` but there is no ads, so I sent an email to adsense to get some help and they told me that there is an issue with dynamic content and I should use ad units.

Your module seems working with Angular, did I miss something ?

I inject adsense code and I got ads before my site loads, so I assume that there is an issue with Angular. I checked source code of your demo and I don't see why it works in your case and not for my website.

The only difference is that I am using lazy loading, is that an issue ?
Have you tried with lazy loading ?
My account is approved, I tried overlay ads and it works.

Thanks, 
Best,

**Comment by scttcper** [comment]
You aren’t missing anything, sometimes the ads just don’t load. I’d push to prod and see what happens with some traffic

**Comment by scttcper** [comment]
Try it with my Adsense code in the readme/demo

**Comment by moises291202** [comment]
> 
> 
> Try it with my Adsense code in the readme/demo

I tried with your adClien and adSlot, and still invisible:

![imagen](https://user-images.githubusercontent.com/25679618/74860773-d10a9280-530e-11ea-9cdc-c79cb138860d.png)
![imagen](https://user-images.githubusercontent.com/25679618/74860791-d962cd80-530e-11ea-9f30-df0fc2fc4a3b.png)

PD: I don't have any issue on the console.

Thanks, by the way

**Comment by scttcper** [comment]
That looks fine. I would launch and assume the ads will start working eventually

**Comment by powerlife000** [comment]
Have the same problem. My ads not showing. I don't have any errrs in the console.

**Comment by eddyoooo** [comment]
> That looks fine. I would launch and assume the ads will start working eventually

It seems data-ad-status="filled/unfilled" is missing though? Why is that? I notice it happens when my ng-adsense is nested in divs. Any ideas?
