### ISSUE TITLE
Angular 7 support for multiple components

### ISSUE THREAD

**Issue by chrisrodriguezmbww** [scttcper/ng2-adsense#359]
I followed your directions and put it in module.ts all necessary info to start.

I get errors by placing in different components.
  `<ng-adsense
    [width]="300"
    [height]="300"
    [className]="horizontal-square">
  </ng-adsense>`

**Comment by chrisrodriguezmbww** [comment]
@scttcper well if you add a component outside root module, like a page, what is the import for that page module?

**Comment by chrisrodriguezmbww** [comment]
@scttcper I have to put this in every component?

    AdsenseModule.forRoot({
      adClient: 'ca-pub-7640562161899788',
      adSlot: 7259870550,
    })

**Comment by scttcper** [comment]
No you would put that at the root module and that’s it

**Comment by chrisrodriguezmbww** [comment]
Well I have to put it in multiple modules with different components.

**Comment by chrisrodriguezmbww** [comment]
@scttcper I am getting 400 errors on my angular site. I am already approved and stuff anyway you can help me and check it out?
