### ISSUE TITLE
Is it just me that this doesn't work on my Angular 8 sites. Error 403

### ISSUE THREAD

**Issue by ericel** [scttcper/ng2-adsense#365]
I have an adsense account. I verified the account with a PHP website as adsense refused to accept my Angular web Application for verification.

Ads do show on the PHP site. But when I place ads on another website which is Angular application, I get the 403 error.

I think adsense doesn't really demand that we add other websites to be able to display ads on them(or does it?).

If not, what would be the way here to display adsense ads on my Angular application?

**Comment by scttcper** [comment]
adsense is just weird. You should deploy the angular app with the ads and watch for a few days. I've got a couple websites using angular 8 and this module. like https://xmplaylist.com/
