### ISSUE TITLE
Ads with size responsive

### ISSUE THREAD

**Issue by marcosybarraa** [scttcper/ng2-adsense#370]
Hi there,
thanks for the development and maintenance of this module.
Current adsense blocks of ads are suggested to not have fix size, but a responsive size, the google code receives 2 params for this :

data-ad-format="auto"
data-full-width-responsive="true"

I dont see the option in the documentation, ¿could be added to the module?
Is a strong suggestion from google.

Kind regards

**Comment by scttcper** [comment]
format is there in the docs.
data-full-width-responsive is for mobile ads and could be added

**Comment by scttcper** [comment]
fullWidthResponsive is in there already tho

**Comment by marcosybarraa** [comment]
For me it does not work, in angular universal SSR.
It does with fix width:height but not with responsive options

**Comment by scttcper** [comment]
everything should be applied in ngOnInit

**Comment by marcosybarraa** [comment]
yes, I do and it is not showing it for me with responsive params.
