### ISSUE TITLE
Angular universal SSR

### ISSUE THREAD

**Issue by Easyschools** [scttcper/ng2-adsense#371]
I am trying to use your Angular universal SSR with your package. which is extremely nice but still I have issue  with the timeout retry function. 
sometime the request to google adsense doesn't get the ads so I have to make timeout retry and call google api again.

The problem is the SSR have to wait for the retry timeout until it gets data so that's really bad for performance and I get high TTFB. So i thought of making the ng adsense html to be run outside angular and worked perfectly but only on second page. but if it's first load page it doesn't get any ad and only works in routing link.

**Comment by JancoBH** [comment]
any update about this? I have the same problem
