### ISSUE TITLE
Adding 'height: auto !important' to all parent containers

### ISSUE THREAD

**Issue by Chifilly** [scttcper/ng2-adsense#380]
I can't seem to find why this is happening in the code of this repo, but with any `ng-adsense` element on a page, after loading, every single parent container for it gets `height: auto !important` added to it (I'm assuming via Javascript since it is added directly to the style and after everything has loaded), which horribly messing the page styles (since it can't be overridden via CSS since it's applied directly in the style, thus height values added via CSS are ignored).

If I remove the ng-adsense element from the page, the style is no longer added.

**Comment by scttcper** [comment]
probably google adsense

**Comment by Chifilly** [comment]
I think you're right on that part. It seems the adsense code does this, because Google like to mess with peoples' pages apparently. I can't seem to find a workaround for this, I'll (try and remember to) post an update here for anyone else with this issue if I find a workaround for it

**Comment by kasameydan** [comment]
same problem here!
@Chifilly did you found workaround ?

**Comment by Blaarkies** [comment]
@kasameydan 
Add `adFormat="inline"` to the `<ng-adsense>` tag, the style don't get applied when this is set. Other values might also work, as long as it does not default to auto
