### ISSUE TITLE
Latest version with removed try-catch breaks pages

### ISSUE THREAD

**Issue by rawoke083** [scttcper/ng2-adsense#399]
HI when I update to latest version 8, I keep getting javascript errors from google-ads:
"No slots available / uncaught", it previously works fine, but now all pages are completely broken when I upgrade to latest version.

**Comment by scttcper** [comment]
fixed in https://github.com/scttcper/ng2-adsense/commit/3235b19460e0422d1dd2252bbd4c88b05c916cce

**Comment by rawoke083** [comment]
Thank you sir ! :)
