### ISSUE TITLE
Images in some of the ads not getting displayed on my website

### ISSUE THREAD

**Issue by IamDeshRaj** [scttcper/ng2-adsense#415]
Images of some of the ads not getting displayed on my website [https://www.mypleaks.com](https://www.mypleaks.com) in chrome even after iframe has rendered correctly. The empty slot mentioned in the below screenshot can be seen on the website. On inspecting these empty slots, it can be seen ads have rendered but the image didn't display.

I'm adding ng-adsense component like this.
`<ng-adsense [adSlot]="2819212735" [width]="344" [height]="350"></ng-adsense>`

![1](https://user-images.githubusercontent.com/6917620/89605864-400f7f80-d88c-11ea-92ed-58e572b7fcaa.JPG)

**Comment by alexisqc92** [comment]
where you able to fix this?

**Comment by IamDeshRaj** [comment]
It got resolved automatically. Probably google fixed it somehow.

**Comment by scttcper** [comment]
Yeah it's really not something to worry about. There isn't always an ad
