### ISSUE TITLE
Question about - disable anchor ads at the top of the page

### ISSUE THREAD

**Issue by naveedahmed1** [scttcper/ng2-adsense#436]
I have a quick question:

If I add the code suggested in below answer to disable anchor ads at the top of the page, will it interfere with ng2-adsense plugin?

https://support.google.com/adsense/answer/7478225?hl=en

Especially below code:

```
<script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-1234567891234567",
    enable_page_level_ads: true,
    overlays: {bottom: true}
  });
</script>
```

**Comment by scttcper** [comment]
It's fine
