### ISSUE TITLE
the ads didnt change 

### ISSUE THREAD

**Issue by OdaiTu** [scttcper/ng2-adsense#70]
im using a component to preview a news so its one component and the user when open this component for first time the ads plugin shows when im still in the same compoenet and open a new news form the side nave for example the content of the news changed but the ads still the same

**Comment by scttcper** [comment]
you'll have to destroy the component. When the next news is loading put an *ngIf on the adsense component and open it again.

**Comment by OdaiTu** [comment]
@scttcper 

how can i don this ? the ads just in html file not ts ?
can you give me an example ?

**Comment by scttcper** [comment]
When loading your new content set `loading = true` and on your adsense component put `*ngIf="!loading"` and when the content loads, set `loading = false` and you will get new ads.

**Comment by OdaiTu** [comment]
@scttcper 
 i did it like this but nothing change
see this is my app

[http://zaina.mezian.co/news/102802](url)

when i open a new news from sidebar or down section the ads still the same
but if i leave the component and re open it again the  ads change normally

**Comment by scttcper** [comment]
Can you link me to the component

**Comment by OdaiTu** [comment]
@scttcper 
[https://drive.google.com/open?id=0Bxp7VVaVN1DqbHZLOERyanhYdm8](url)

**Comment by scttcper** [comment]
In your component you're only setting loading to true once. It needs to happen every time you load a new article. Put `this.loading = true` inside your route params subscription `this.route.params.subscribe(params => {`

**Comment by OdaiTu** [comment]
@scttcper 
i was puting it there but ok nice an where to put the loading to false exactly ?

**Comment by scttcper** [comment]
You have it in the right place

**Comment by OdaiTu** [comment]
@scttcper 

its the same problem bro :(

**Comment by scttcper** [comment]
I've added it to the preview https://scttcper.github.io/ng2-adsense/#/ads/2
page 3 and page 4 is now a single route that has its params change. Ads are refreshed using setTimeout instead of an api call.

**Comment by OdaiTu** [comment]
thannnk you !
its worked
