### ISSUE TITLE
Angular 4 Production Build Prerender Mode (Angular Universal)

### ISSUE THREAD

**Issue by naveedahmed1** [scttcper/ng2-adsense#80]
Hi,

I was wondering how this would work with Angular App in Production with Prerendering (Angular Universal).

Have you tried it? does it load ads on server side in case of prerendering?

**Comment by scttcper** [comment]
It won't load ads on the server since Adsense.js is loaded async in the browser. I haven't tried it yet but I would be worried that nothing would show at all until next page load

**Comment by sdsanders** [comment]
I recently implemented this in an Angular Universal project and it worked just fine. The ad doesn't load when rendered by the server, but then renders during the "handoff" and bootstrap of the client-side app.

**Comment by scttcper** [comment]
@sdsanders thanks for trying it out 🎉

**Comment by naveedahmed1** [comment]
That's awesome @sdsanders, will be trying in my project soon :)

**Comment by naveedahmed1** [comment]
@sdsanders I tried it on Universal but it doesn't seem to work. When the page is first loaded:

- When response from server is received : no ad is loaded (makes sense)

- When the client side code loads and syncs the dom: still not ad loaded (I assume you are saying that you see ad at this stage)

- When spa is fully active and I navigate to another page with ad: its show ads as normal

I have `<script async src=//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js></script>` at the bottom of my `index.html` page. Are you adding it dynamically?

**Comment by shamank** [comment]
@scttcper I'm not being able to make it work in Angular 4 for Ionic 3. It loads sometimes, but most of the times, it shows an empty box (transparent box). I can see all the HTML there, but there's race condition somewhere. I'm not sure if it's due to Angular 4 renderer however. Is there some way I can run `(window['adsbygoogle'] = window['adsbygoogle'] || []).push({})` on demand or with some delay?

**Comment by shamank** [comment]
nm I saw the code and you are already doing that.

**Comment by vptcnt** [comment]
@shamank Hello,

Did you success to run ng2-adsense with Ionic 3 ?
I have the same problem. Sometimes there is no banner.

Vincent

**Comment by shamank** [comment]
Yes. There's no banner in dev mode because of Google limitations on local
environments. It works good in prod however.
