### ISSUE TITLE
Global defaults when using Lazyloading

### ISSUE THREAD

**Issue by naveedahmed1** [scttcper/ng2-adsense#97]
Can you please guide if the same configuration should be used for Lazyloaded modules as well?

I mean docs suggests importing module like this:

```
    AdsenseModule.forRoot({
      adClient: 'ca-pub-4543543545',
      adSlot: 45435435
    }),
```

Whereas, if I am not wrong forRoot should be used on the root module only. Should we add
AdsenseModule.forRoot or AdsenseModule in Lazyloaded modules?

**Comment by scttcper** [comment]
forRoot should only be on root module. AdsenseModule without forRoot should be used in any child modules.  

Let me know if you run into any issues.

**Comment by naveedahmed1** [comment]
Thank you so much @scttcper for your reply, Will it automatically pick the publisher (i.e. adClient) from the root module?

**Comment by scttcper** [comment]
Yep. I think forChild is only necessary when you want to add more data when the lazy module is loaded. Like the router adds additional routes in the lazy child. Loading AdsenseModule in the lazy module will ask the parent module for the already existing AdsenseModule w/ settings.

**Comment by naveedahmed1** [comment]
It seems that Adsense is taking impression on each ad unit as a page view, can you please check it on your end if you notice similar on your side?

**Comment by naveedahmed1** [comment]
Here we have just one ins tag on which all properties are applied depending on the users settings:

https://github.com/scttcper/ng2-adsense/blob/22fb12d1b8b1f50fe0350f92735e33fc3ddf45bf/src/lib/ng2-adsense.ts#L41

What if we could add another input to this component adType and the appropriate inc tag is added depending on the selected adType:

```
<div [ngSwitch]="adType" >
    <ins *ngSwitchCase="'responsive'" class="adsbygoogle"
        [ngStyle]="{'display': 'block'}"
        [attr.data-ad-client]="adClient"
        [attr.data-ad-slot]="adSlot"
        [attr.data-ad-format]="'auto'">
    </ins>

 <ins  *ngSwitchCase="'fixedDimensions'" class="adsbygoogle"
    [ngStyle]="{'display': display, 'width.px': width, 'height.px': height }"
    [attr.data-ad-client]="adClient"
    [attr.data-ad-slot]="adSlot">
  </ins>

...
....


</div>
```

**Comment by scttcper** [comment]
I think you would have to set the `adRegion` manually

**Comment by naveedahmed1** [comment]
So, all units on a specific page should have same value for adRegion ?
